{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-aiops-investigator.serviceAccountName" . }}
  labels:
    {{- include "k8s-aiops-investigator.labels" . | nindent 4 }}
{{- end }}

